ARG PARENT_IMAGE=rlworkgroup/metarl-base
FROM $PARENT_IMAGE

# Add code stub last
COPY . /root/code/metarl

# Build and install the sdist
RUN python3 setup.py sdist && \
    cp /root/code/metarl/dist/*.tar.gz /root/code/metarl/dist/metarl.tar.gz && \
    pip3 install dist/metarl.tar.gz[all,dev] && \
    rm -r /root/.cache/pip
