version: '2.2'
services:
  metarl-base:
    build:
      cache_from:
        - rlworkgroup/metarl-ci:latest
      context: ../
      dockerfile: docker/Dockerfile.base.18.04
    image: rlworkgroup/metarl-base
  metarl-ci-no-files:
    build:
      cache_from:
        - rlworkgroup/metarl-ci:latest
      context: ../
      dockerfile: docker/Dockerfile.headless
      args:
        - PARENT_IMAGE=rlworkgroup/metarl-base
    image: rlworkgroup/metarl-ci-no-files
  metarl-ci:
    build:
      cache_from:
        - rlworkgroup/metarl-ci:latest
      context: ../
      dockerfile: docker/Dockerfile.runtime
      args:
        - PARENT_IMAGE=rlworkgroup/metarl-ci-no-files
    image: ${TAG}
